package adbfastboot;


import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author javad
 */
public class fastbootadb1 extends javax.swing.JFrame {
    

    /**
     * Creates new form fastbootadb1
     */
    public fastbootadb1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        fastbootReboot = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        adbTextArea = new javax.swing.JTextArea();
        batteryMocking = new javax.swing.JButton();
        screenshotBtn = new javax.swing.JButton();
        screenRecordBtn = new javax.swing.JButton();
        SamsungFRPBtn = new javax.swing.JButton();
        DiagEnableBtn1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        connectBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        readInfoBtn = new javax.swing.JButton();
        rebootBtn = new javax.swing.JButton();
        bootloaderUnlockBtn = new javax.swing.JButton();
        readCidBtn = new javax.swing.JButton();
        readProductBtn = new javax.swing.JButton();
        wipeDataBtn = new javax.swing.JButton();
        lenovoFrp = new javax.swing.JButton();
        yuFrp = new javax.swing.JButton();
        motoNwFix = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        edlFlashing = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fastboot ADB Tool");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jTabbedPane1.setBackground(new java.awt.Color(0, 0, 0));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTabbedPane1.setForeground(new java.awt.Color(0, 51, 51));
        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setForeground(new java.awt.Color(0, 0, 102));

        fastbootReboot.setBackground(new java.awt.Color(0, 0, 0));
        fastbootReboot.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        fastbootReboot.setForeground(new java.awt.Color(255, 255, 255));
        fastbootReboot.setText("Reboot to Fastboot");
        fastbootReboot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fastbootRebootActionPerformed(evt);
            }
        });

        adbTextArea.setColumns(20);
        adbTextArea.setRows(5);
        adbTextArea.setWrapStyleWord(true);
        jScrollPane2.setViewportView(adbTextArea);

        batteryMocking.setBackground(new java.awt.Color(0, 0, 0));
        batteryMocking.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        batteryMocking.setForeground(new java.awt.Color(255, 255, 255));
        batteryMocking.setText("Battery Mocking");
        batteryMocking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batteryMockingActionPerformed(evt);
            }
        });

        screenshotBtn.setBackground(new java.awt.Color(0, 0, 0));
        screenshotBtn.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        screenshotBtn.setForeground(new java.awt.Color(255, 255, 255));
        screenshotBtn.setText("Screeenshot");
        screenshotBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                screenshotBtnActionPerformed(evt);
            }
        });

        screenRecordBtn.setBackground(new java.awt.Color(0, 0, 0));
        screenRecordBtn.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        screenRecordBtn.setForeground(new java.awt.Color(255, 255, 255));
        screenRecordBtn.setText("Screen Record");
        screenRecordBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                screenRecordBtnActionPerformed(evt);
            }
        });

        SamsungFRPBtn.setBackground(new java.awt.Color(0, 0, 0));
        SamsungFRPBtn.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        SamsungFRPBtn.setForeground(new java.awt.Color(255, 255, 255));
        SamsungFRPBtn.setText("Samsung Frp");
        SamsungFRPBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SamsungFRPBtnActionPerformed(evt);
            }
        });

        DiagEnableBtn1.setBackground(new java.awt.Color(0, 0, 0));
        DiagEnableBtn1.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        DiagEnableBtn1.setForeground(new java.awt.Color(255, 255, 255));
        DiagEnableBtn1.setText("Diag Enable");
        DiagEnableBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiagEnableBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fastbootReboot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(batteryMocking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(screenshotBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(screenRecordBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SamsungFRPBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DiagEnableBtn1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(200, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(fastbootReboot)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(batteryMocking)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(screenshotBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(screenRecordBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SamsungFRPBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DiagEnableBtn1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(485, 485, 485))
        );

        jTabbedPane1.addTab("ADB", jPanel2);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setForeground(new java.awt.Color(102, 153, 255));
        jPanel1.setAutoscrolls(true);
        jPanel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));

        connectBtn.setBackground(new java.awt.Color(0, 0, 0));
        connectBtn.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        connectBtn.setForeground(new java.awt.Color(255, 255, 255));
        connectBtn.setText("Connect");
        connectBtn.setMaximumSize(new java.awt.Dimension(103, 25));
        connectBtn.setMinimumSize(new java.awt.Dimension(103, 25));
        connectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectBtnActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(0, 0, 102));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        readInfoBtn.setBackground(new java.awt.Color(0, 0, 0));
        readInfoBtn.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        readInfoBtn.setForeground(new java.awt.Color(255, 255, 255));
        readInfoBtn.setText("Read info");
        readInfoBtn.setMaximumSize(new java.awt.Dimension(103, 25));
        readInfoBtn.setMinimumSize(new java.awt.Dimension(103, 25));
        readInfoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readInfoBtnActionPerformed(evt);
            }
        });

        rebootBtn.setBackground(new java.awt.Color(0, 0, 0));
        rebootBtn.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        rebootBtn.setForeground(new java.awt.Color(255, 255, 255));
        rebootBtn.setText("Reboot");
        rebootBtn.setMaximumSize(new java.awt.Dimension(103, 25));
        rebootBtn.setMinimumSize(new java.awt.Dimension(103, 25));
        rebootBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rebootBtnActionPerformed(evt);
            }
        });

        bootloaderUnlockBtn.setBackground(new java.awt.Color(0, 0, 0));
        bootloaderUnlockBtn.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        bootloaderUnlockBtn.setForeground(new java.awt.Color(255, 255, 255));
        bootloaderUnlockBtn.setText("Bootloader Unlock");
        bootloaderUnlockBtn.setMaximumSize(new java.awt.Dimension(103, 25));
        bootloaderUnlockBtn.setMinimumSize(new java.awt.Dimension(103, 25));
        bootloaderUnlockBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bootloaderUnlockBtnActionPerformed(evt);
            }
        });

        readCidBtn.setBackground(new java.awt.Color(0, 0, 0));
        readCidBtn.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        readCidBtn.setForeground(new java.awt.Color(255, 255, 255));
        readCidBtn.setText("Read CID");
        readCidBtn.setMaximumSize(new java.awt.Dimension(103, 25));
        readCidBtn.setMinimumSize(new java.awt.Dimension(103, 25));
        readCidBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readCidBtnActionPerformed(evt);
            }
        });

        readProductBtn.setBackground(new java.awt.Color(0, 0, 0));
        readProductBtn.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        readProductBtn.setForeground(new java.awt.Color(255, 255, 255));
        readProductBtn.setText("Read Product");
        readProductBtn.setMaximumSize(new java.awt.Dimension(103, 25));
        readProductBtn.setMinimumSize(new java.awt.Dimension(103, 25));
        readProductBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readProductBtnActionPerformed(evt);
            }
        });

        wipeDataBtn.setBackground(new java.awt.Color(0, 0, 0));
        wipeDataBtn.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        wipeDataBtn.setForeground(new java.awt.Color(255, 255, 255));
        wipeDataBtn.setText("Wipe Data");
        wipeDataBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wipeDataBtnActionPerformed(evt);
            }
        });

        lenovoFrp.setBackground(new java.awt.Color(0, 0, 0));
        lenovoFrp.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        lenovoFrp.setForeground(new java.awt.Color(255, 255, 255));
        lenovoFrp.setText("Lenovo FRP");
        lenovoFrp.setMaximumSize(new java.awt.Dimension(103, 25));
        lenovoFrp.setMinimumSize(new java.awt.Dimension(103, 25));
        lenovoFrp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lenovoFrpActionPerformed(evt);
            }
        });

        yuFrp.setBackground(new java.awt.Color(0, 0, 0));
        yuFrp.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        yuFrp.setForeground(new java.awt.Color(255, 255, 255));
        yuFrp.setText("YU FRP");
        yuFrp.setMaximumSize(new java.awt.Dimension(103, 25));
        yuFrp.setMinimumSize(new java.awt.Dimension(103, 25));
        yuFrp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yuFrpActionPerformed(evt);
            }
        });

        motoNwFix.setBackground(new java.awt.Color(0, 0, 0));
        motoNwFix.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        motoNwFix.setForeground(new java.awt.Color(255, 255, 255));
        motoNwFix.setText("Moto Network Fix");
        motoNwFix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motoNwFixActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(connectBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(readProductBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(readCidBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rebootBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(readInfoBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bootloaderUnlockBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(wipeDataBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(motoNwFix, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(yuFrp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lenovoFrp, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(134, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(connectBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(readProductBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(readInfoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lenovoFrp, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(motoNwFix, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rebootBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bootloaderUnlockBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yuFrp, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(readCidBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(wipeDataBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(237, 237, 237))
        );

        jTabbedPane1.addTab("Fastboot", jPanel1);

        edlFlashing.setText("Flashing");
        edlFlashing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edlFlashingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(edlFlashing)
                .addContainerGap(656, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(edlFlashing)
                .addContainerGap(513, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Qualcomm", jPanel3);

        jDesktopPane1.setLayer(jTabbedPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 762, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Fastboot");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void connectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectBtnActionPerformed
 
   String k;
        jTextArea1.setText(null);
		GetCmdResult R=new GetCmdResult();
		k=R.getResult("fastboot devices");
		jTextArea1.append(k+"\n"); 
        
            
            
       
    }//GEN-LAST:event_connectBtnActionPerformed

    private void readInfoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readInfoBtnActionPerformed
        String k;
        jTextArea1.setText(null);
		GetCmdResult R=new GetCmdResult();
		k=R.getResult("fastboot getvar all");
		jTextArea1.append(k+"\n");
    }//GEN-LAST:event_readInfoBtnActionPerformed

    private void rebootBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rebootBtnActionPerformed
        jTextArea1.setText(null);  
        GetCmdResult obj=new GetCmdResult();
          String k =obj.getResult("fastboot reboot");
          jTextArea1.append(k);
          
    }//GEN-LAST:event_rebootBtnActionPerformed

    private void bootloaderUnlockBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bootloaderUnlockBtnActionPerformed
      jTextArea1.setText("");
        jTextArea1.append("only old model handsets unlocked by this function\n");
      jTextArea1.append("It Will Void Your Hanset's Warranty\n");
        GetCmdResult obj=new GetCmdResult();
          String k =obj.getResult("fastboot oem unlock");
          jTextArea1.append(k);
    }//GEN-LAST:event_bootloaderUnlockBtnActionPerformed

    private void fastbootRebootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fastbootRebootActionPerformed
       String k;
       adbTextArea.setText(null);
       
        AdbCmds C=new AdbCmds();
        k=C.getResult("adb reboot bootloader");
        adbTextArea.append(k);
       
          // TODO add your handling code here:
    }//GEN-LAST:event_fastbootRebootActionPerformed

    private void readCidBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readCidBtnActionPerformed
     String k;
        jTextArea1.setText(null);
		GetCmdResult R=new GetCmdResult();
		k=R.getResult("fastboot getvar cid");
		jTextArea1.append(k+"\n"); // TODO add your handling code here:
    }//GEN-LAST:event_readCidBtnActionPerformed
    
    private void readProductBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readProductBtnActionPerformed
      
String k;
        jTextArea1.setText(null);
		GetCmdResult R=new GetCmdResult();
		k=R.getResult("fastboot getvar product");
		jTextArea1.append(k+"\n");
     
    }//GEN-LAST:event_readProductBtnActionPerformed
    
    private void wipeDataBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wipeDataBtnActionPerformed
    String k;
        jTextArea1.setText(null);
		GetCmdResult R=new GetCmdResult();
		k=R.getResult("fastboot -w");
		jTextArea1.append(k+"\n");  
    }//GEN-LAST:event_wipeDataBtnActionPerformed
    
    private void batteryMockingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batteryMockingActionPerformed

        BatteryMocking1 bm=new BatteryMocking1(); 
     bm.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_batteryMockingActionPerformed

    private void SamsungFRPBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SamsungFRPBtnActionPerformed
String s = null;
     

        try {
            
	    // run the Unix "ps -ef" command
            // using the Runtime exec method:
            Process p = Runtime.getRuntime().exec("adb shell am start -n com.google.android.gsf.login/");
          
            
            BufferedReader stdInput = new BufferedReader(new 
                 InputStreamReader(p.getInputStream()));

            BufferedReader stdError = new BufferedReader(new 
                 InputStreamReader(p.getErrorStream()));

            // read the output from the command
            System.out.println("Here is the standard output of the command:\n");
            while ((s = stdInput.readLine()) != null) {
                adbTextArea.setText(s);
            }
            
            // read any errors from the attempted command
            System.out.println("Here is the standard error of the command (if any):\n");
            while ((s = stdError.readLine()) != null) {
                adbTextArea.append(s+"\n");
                    
            }
        }
         catch (IOException e) {
            System.out.println("exception happened - here's what I know: ");
            e.printStackTrace();
            System.exit(-1);
         }
    }//GEN-LAST:event_SamsungFRPBtnActionPerformed

    
    private void screenshotBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_screenshotBtnActionPerformed
     
String k;
       adbTextArea.setText(null);
       
        AdbCmds C=new AdbCmds();
        k=C.getResult("adb shell screencap /sdcard/screen.png");
        
        adbTextArea.append(k);
       k=C.getResult("adb pull /sdcard/screen.png");
       adbTextArea.append(k);
        
        
    }//GEN-LAST:event_screenshotBtnActionPerformed

    private void screenRecordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_screenRecordBtnActionPerformed
       
  String k;
       adbTextArea.setText(null);
       
        AdbCmds C=new AdbCmds();
        k=C.getResult("adb shell screenrecord /sdcard/screen.mp4");
        
        adbTextArea.append(k);
       k=C.getResult("adb pull /sdcard/screen.mp4");
       adbTextArea.append(k);
    }//GEN-LAST:event_screenRecordBtnActionPerformed

    private void lenovoFrpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lenovoFrpActionPerformed
        String k;
        jTextArea1.setText(null);
		GetCmdResult R=new GetCmdResult();
		k=R.getResult("fastboot erase config");
		jTextArea1.append(k+"\n");// TODO add your handling code here:
    }//GEN-LAST:event_lenovoFrpActionPerformed

    private void yuFrpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yuFrpActionPerformed
       String k;
        jTextArea1.setText(null);
		GetCmdResult R=new GetCmdResult();
		k=R.getResult("Fastboot -i 0x2a96 erase config");
		jTextArea1.append(k+"\n"); // TODO add your handling code here:
    }//GEN-LAST:event_yuFrpActionPerformed

    private void motoNwFixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motoNwFixActionPerformed
       String k;
        jTextArea1.setText(null);
		GetCmdResult R=new GetCmdResult();
		k=R.getResult("Fastboot oem config bootmode \"\"");
		jTextArea1.append(k+"\n");
                k=R.getResult("Fastboot oem fb_mode_clear");
		jTextArea1.append(k+"\n");
                k=R.getResult("Fastboot reboot");
		jTextArea1.append(k+"\n");
    }//GEN-LAST:event_motoNwFixActionPerformed

    private void DiagEnableBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiagEnableBtn1ActionPerformed
        String k;
        adbTextArea.setText("!!!!PHONE MUST BE ROOTED!!!!");
        RunCommand R=new RunCommand();
        k=R.getResult("adb shell");
        adbTextArea.append(k+"\n");
        k=R.getResult("su");
        adbTextArea.append(k+"\n");
        k=R.getResult("setprop sys.usb.config diag,adb");
        adbTextArea.append(k+"\n"); // TODO add your handling code here:
    }//GEN-LAST:event_DiagEnableBtn1ActionPerformed

    private void edlFlashingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edlFlashingActionPerformed
edlFlashing f=new edlFlashing();
f.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_edlFlashingActionPerformed
 
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fastbootadb1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fastbootadb1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fastbootadb1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fastbootadb1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fastbootadb1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DiagEnableBtn1;
    private javax.swing.JButton SamsungFRPBtn;
    private javax.swing.JTextArea adbTextArea;
    private javax.swing.JButton batteryMocking;
    private javax.swing.JButton bootloaderUnlockBtn;
    private javax.swing.JButton connectBtn;
    private javax.swing.JButton edlFlashing;
    private javax.swing.JButton fastbootReboot;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton lenovoFrp;
    private javax.swing.JButton motoNwFix;
    private javax.swing.JButton readCidBtn;
    private javax.swing.JButton readInfoBtn;
    private javax.swing.JButton readProductBtn;
    private javax.swing.JButton rebootBtn;
    private javax.swing.JButton screenRecordBtn;
    private javax.swing.JButton screenshotBtn;
    private javax.swing.JButton wipeDataBtn;
    private javax.swing.JButton yuFrp;
    // End of variables declaration//GEN-END:variables
}
